// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: annual_transactions.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAnnualTransaction = `-- name: CreateAnnualTransaction :one
INSERT INTO annual_transactions (
    user_id,
    name,
    value,
    day,
    month,
    category_id,
    credit_card_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, user_id, name, value, day, month, category_id, credit_card_id, created_at, updated_at
`

type CreateAnnualTransactionParams struct {
	UserID       uuid.UUID      `json:"user_id"`
	Name         string         `json:"name"`
	Value        pgtype.Numeric `json:"value"`
	Day          int32          `json:"day"`
	Month        int32          `json:"month"`
	CategoryID   uuid.UUID      `json:"category_id"`
	CreditCardID pgtype.UUID    `json:"credit_card_id"`
}

func (q *Queries) CreateAnnualTransaction(ctx context.Context, arg CreateAnnualTransactionParams) (AnnualTransaction, error) {
	row := q.db.QueryRow(ctx, createAnnualTransaction,
		arg.UserID,
		arg.Name,
		arg.Value,
		arg.Day,
		arg.Month,
		arg.CategoryID,
		arg.CreditCardID,
	)
	var i AnnualTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Value,
		&i.Day,
		&i.Month,
		&i.CategoryID,
		&i.CreditCardID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAnnualTransaction = `-- name: DeleteAnnualTransaction :exec
DELETE FROM annual_transactions
WHERE id = $1
`

func (q *Queries) DeleteAnnualTransaction(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAnnualTransaction, id)
	return err
}

const getAnnualTransactionByID = `-- name: GetAnnualTransactionByID :one
SELECT id, user_id, name, value, day, month, category_id, credit_card_id, created_at, updated_at
FROM annual_transactions
WHERE id = $1
`

func (q *Queries) GetAnnualTransactionByID(ctx context.Context, id uuid.UUID) (AnnualTransaction, error) {
	row := q.db.QueryRow(ctx, getAnnualTransactionByID, id)
	var i AnnualTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Value,
		&i.Day,
		&i.Month,
		&i.CategoryID,
		&i.CreditCardID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAnnualTransactionsByUserIDPaginated = `-- name: ListAnnualTransactionsByUserIDPaginated :many
SELECT 
    id,
    user_id,
    name,
    value,
    day,
    month,
    category_id,
    credit_card_id,
    created_at,
    updated_at,
    COUNT(*) OVER() as total_count
FROM annual_transactions
WHERE user_id = $1
ORDER BY month ASC, day ASC
LIMIT $2 OFFSET $3
`

type ListAnnualTransactionsByUserIDPaginatedParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListAnnualTransactionsByUserIDPaginatedRow struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	Name         string             `json:"name"`
	Value        pgtype.Numeric     `json:"value"`
	Day          int32              `json:"day"`
	Month        int32              `json:"month"`
	CategoryID   uuid.UUID          `json:"category_id"`
	CreditCardID pgtype.UUID        `json:"credit_card_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	TotalCount   int64              `json:"total_count"`
}

func (q *Queries) ListAnnualTransactionsByUserIDPaginated(ctx context.Context, arg ListAnnualTransactionsByUserIDPaginatedParams) ([]ListAnnualTransactionsByUserIDPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listAnnualTransactionsByUserIDPaginated, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAnnualTransactionsByUserIDPaginatedRow
	for rows.Next() {
		var i ListAnnualTransactionsByUserIDPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Value,
			&i.Day,
			&i.Month,
			&i.CategoryID,
			&i.CreditCardID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnnualTransaction = `-- name: UpdateAnnualTransaction :one
UPDATE annual_transactions
SET
    name = $2,
    value = $3,
    day = $4,
    month = $5,
    category_id = $6,
    credit_card_id = $7,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, value, day, month, category_id, credit_card_id, created_at, updated_at
`

type UpdateAnnualTransactionParams struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	Value        pgtype.Numeric `json:"value"`
	Day          int32          `json:"day"`
	Month        int32          `json:"month"`
	CategoryID   uuid.UUID      `json:"category_id"`
	CreditCardID pgtype.UUID    `json:"credit_card_id"`
}

func (q *Queries) UpdateAnnualTransaction(ctx context.Context, arg UpdateAnnualTransactionParams) (AnnualTransaction, error) {
	row := q.db.QueryRow(ctx, updateAnnualTransaction,
		arg.ID,
		arg.Name,
		arg.Value,
		arg.Day,
		arg.Month,
		arg.CategoryID,
		arg.CreditCardID,
	)
	var i AnnualTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Value,
		&i.Day,
		&i.Month,
		&i.CategoryID,
		&i.CreditCardID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
