// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const countCategoriesByUserID = `-- name: CountCategoriesByUserID :one
SELECT COUNT(*) as total
FROM categories
WHERE user_id = $1
`

func (q *Queries) CountCategoriesByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCategoriesByUserID, userID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (
    user_id,
    transaction_type,
    name,
    icon
) VALUES (
    $1, $2, $3, $4
) RETURNING id, user_id, transaction_type, name, icon, created_at, updated_at
`

type CreateCategoryParams struct {
	UserID          uuid.UUID `json:"user_id"`
	TransactionType int32     `json:"transaction_type"`
	Name            string    `json:"name"`
	Icon            string    `json:"icon"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.UserID,
		arg.TransactionType,
		arg.Name,
		arg.Icon,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TransactionType,
		&i.Name,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoriesByUserID = `-- name: GetCategoriesByUserID :many
SELECT id, user_id, transaction_type, name, icon, created_at, updated_at
FROM categories
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetCategoriesByUserID(ctx context.Context, userID uuid.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, getCategoriesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TransactionType,
			&i.Name,
			&i.Icon,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, user_id, transaction_type, name, icon, created_at, updated_at
FROM categories
WHERE id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TransactionType,
		&i.Name,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
