// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: creditcards.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const countCreditCardsByUserID = `-- name: CountCreditCardsByUserID :one
SELECT COUNT(*) as total
FROM credit_cards
WHERE user_id = $1
`

func (q *Queries) CountCreditCardsByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCreditCardsByUserID, userID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createCreditCard = `-- name: CreateCreditCard :one
INSERT INTO credit_cards (
    user_id, 
    name, 
    first_four_numbers, 
    credit_limit, 
    close_day, 
    expire_day,
    background_color,
    text_color
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, user_id, name, first_four_numbers, credit_limit, close_day, expire_day, background_color, text_color, created_at, updated_at
`

type CreateCreditCardParams struct {
	UserID           uuid.UUID `json:"user_id"`
	Name             string    `json:"name"`
	FirstFourNumbers string    `json:"first_four_numbers"`
	CreditLimit      float64   `json:"credit_limit"`
	CloseDay         int32     `json:"close_day"`
	ExpireDay        int32     `json:"expire_day"`
	BackgroundColor  string    `json:"background_color"`
	TextColor        string    `json:"text_color"`
}

func (q *Queries) CreateCreditCard(ctx context.Context, arg CreateCreditCardParams) (CreditCard, error) {
	row := q.db.QueryRow(ctx, createCreditCard,
		arg.UserID,
		arg.Name,
		arg.FirstFourNumbers,
		arg.CreditLimit,
		arg.CloseDay,
		arg.ExpireDay,
		arg.BackgroundColor,
		arg.TextColor,
	)
	var i CreditCard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.FirstFourNumbers,
		&i.CreditLimit,
		&i.CloseDay,
		&i.ExpireDay,
		&i.BackgroundColor,
		&i.TextColor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCreditCard = `-- name: DeleteCreditCard :exec
DELETE FROM credit_cards
WHERE id = $1
`

func (q *Queries) DeleteCreditCard(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCreditCard, id)
	return err
}

const getCreditCardByID = `-- name: GetCreditCardByID :one
SELECT id, user_id, name, first_four_numbers, credit_limit, close_day, expire_day, background_color, text_color, created_at, updated_at 
FROM credit_cards
WHERE id = $1
`

func (q *Queries) GetCreditCardByID(ctx context.Context, id uuid.UUID) (CreditCard, error) {
	row := q.db.QueryRow(ctx, getCreditCardByID, id)
	var i CreditCard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.FirstFourNumbers,
		&i.CreditLimit,
		&i.CloseDay,
		&i.ExpireDay,
		&i.BackgroundColor,
		&i.TextColor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCreditCards = `-- name: ListCreditCards :many
SELECT id, user_id, name, first_four_numbers, credit_limit, close_day, expire_day, background_color, text_color, created_at, updated_at 
FROM credit_cards
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCreditCards(ctx context.Context, userID uuid.UUID) ([]CreditCard, error) {
	rows, err := q.db.Query(ctx, listCreditCards, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreditCard
	for rows.Next() {
		var i CreditCard
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.FirstFourNumbers,
			&i.CreditLimit,
			&i.CloseDay,
			&i.ExpireDay,
			&i.BackgroundColor,
			&i.TextColor,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCreditCard = `-- name: UpdateCreditCard :one
UPDATE credit_cards
SET
    name = $2,
    first_four_numbers = $3,
    credit_limit = $4,
    close_day = $5,
    expire_day = $6,
    background_color = $7,
    text_color = $8,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, first_four_numbers, credit_limit, close_day, expire_day, background_color, text_color, created_at, updated_at
`

type UpdateCreditCardParams struct {
	ID               uuid.UUID `json:"id"`
	Name             string    `json:"name"`
	FirstFourNumbers string    `json:"first_four_numbers"`
	CreditLimit      float64   `json:"credit_limit"`
	CloseDay         int32     `json:"close_day"`
	ExpireDay        int32     `json:"expire_day"`
	BackgroundColor  string    `json:"background_color"`
	TextColor        string    `json:"text_color"`
}

func (q *Queries) UpdateCreditCard(ctx context.Context, arg UpdateCreditCardParams) (CreditCard, error) {
	row := q.db.QueryRow(ctx, updateCreditCard,
		arg.ID,
		arg.Name,
		arg.FirstFourNumbers,
		arg.CreditLimit,
		arg.CloseDay,
		arg.ExpireDay,
		arg.BackgroundColor,
		arg.TextColor,
	)
	var i CreditCard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.FirstFourNumbers,
		&i.CreditLimit,
		&i.CloseDay,
		&i.ExpireDay,
		&i.BackgroundColor,
		&i.TextColor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
