// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: installment_transaction.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInstallmentTransaction = `-- name: CreateInstallmentTransaction :one
INSERT INTO installment_transactions (
    user_id,
    name,
    value,
    initial_date,
    final_date,
    category_id,
    credit_card_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, user_id, name, value, initial_date, final_date, category_id, credit_card_id, created_at, updated_at
`

type CreateInstallmentTransactionParams struct {
	UserID       uuid.UUID          `json:"user_id"`
	Name         string             `json:"name"`
	Value        pgtype.Numeric     `json:"value"`
	InitialDate  pgtype.Timestamptz `json:"initial_date"`
	FinalDate    pgtype.Timestamptz `json:"final_date"`
	CategoryID   uuid.UUID          `json:"category_id"`
	CreditCardID pgtype.UUID        `json:"credit_card_id"`
}

func (q *Queries) CreateInstallmentTransaction(ctx context.Context, arg CreateInstallmentTransactionParams) (InstallmentTransaction, error) {
	row := q.db.QueryRow(ctx, createInstallmentTransaction,
		arg.UserID,
		arg.Name,
		arg.Value,
		arg.InitialDate,
		arg.FinalDate,
		arg.CategoryID,
		arg.CreditCardID,
	)
	var i InstallmentTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Value,
		&i.InitialDate,
		&i.FinalDate,
		&i.CategoryID,
		&i.CreditCardID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInstallmentTransaction = `-- name: DeleteInstallmentTransaction :exec
DELETE FROM installment_transactions
WHERE id = $1
`

func (q *Queries) DeleteInstallmentTransaction(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInstallmentTransaction, id)
	return err
}

const getInstallmentTransactionByID = `-- name: GetInstallmentTransactionByID :one
SELECT id, user_id, name, value, initial_date, final_date, category_id, credit_card_id, created_at, updated_at
FROM installment_transactions
WHERE id = $1
`

func (q *Queries) GetInstallmentTransactionByID(ctx context.Context, id uuid.UUID) (InstallmentTransaction, error) {
	row := q.db.QueryRow(ctx, getInstallmentTransactionByID, id)
	var i InstallmentTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Value,
		&i.InitialDate,
		&i.FinalDate,
		&i.CategoryID,
		&i.CreditCardID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInstallmentTransactionsByUserIDPaginated = `-- name: ListInstallmentTransactionsByUserIDPaginated :many
SELECT 
    id,
    user_id,
    name,
    value,
    initial_date,
    final_date,
    category_id,
    credit_card_id,
    created_at,
    updated_at,
    COUNT(*) OVER() as total_count
FROM installment_transactions
WHERE user_id = $1
ORDER BY initial_date DESC
LIMIT $2 OFFSET $3
`

type ListInstallmentTransactionsByUserIDPaginatedParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListInstallmentTransactionsByUserIDPaginatedRow struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	Name         string             `json:"name"`
	Value        pgtype.Numeric     `json:"value"`
	InitialDate  pgtype.Timestamptz `json:"initial_date"`
	FinalDate    pgtype.Timestamptz `json:"final_date"`
	CategoryID   uuid.UUID          `json:"category_id"`
	CreditCardID pgtype.UUID        `json:"credit_card_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	TotalCount   int64              `json:"total_count"`
}

func (q *Queries) ListInstallmentTransactionsByUserIDPaginated(ctx context.Context, arg ListInstallmentTransactionsByUserIDPaginatedParams) ([]ListInstallmentTransactionsByUserIDPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listInstallmentTransactionsByUserIDPaginated, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInstallmentTransactionsByUserIDPaginatedRow
	for rows.Next() {
		var i ListInstallmentTransactionsByUserIDPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Value,
			&i.InitialDate,
			&i.FinalDate,
			&i.CategoryID,
			&i.CreditCardID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInstallmentTransaction = `-- name: UpdateInstallmentTransaction :one
UPDATE installment_transactions
SET
    name = $2,
    value = $3,
    initial_date = $4,
    final_date = $5,
    category_id = $6,
    credit_card_id = $7,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, value, initial_date, final_date, category_id, credit_card_id, created_at, updated_at
`

type UpdateInstallmentTransactionParams struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	Value        pgtype.Numeric     `json:"value"`
	InitialDate  pgtype.Timestamptz `json:"initial_date"`
	FinalDate    pgtype.Timestamptz `json:"final_date"`
	CategoryID   uuid.UUID          `json:"category_id"`
	CreditCardID pgtype.UUID        `json:"credit_card_id"`
}

func (q *Queries) UpdateInstallmentTransaction(ctx context.Context, arg UpdateInstallmentTransactionParams) (InstallmentTransaction, error) {
	row := q.db.QueryRow(ctx, updateInstallmentTransaction,
		arg.ID,
		arg.Name,
		arg.Value,
		arg.InitialDate,
		arg.FinalDate,
		arg.CategoryID,
		arg.CreditCardID,
	)
	var i InstallmentTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Value,
		&i.InitialDate,
		&i.FinalDate,
		&i.CategoryID,
		&i.CreditCardID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
