// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: monthly_transactions.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMonthlyTransaction = `-- name: CreateMonthlyTransaction :one
INSERT INTO monthly_transactions (
    user_id,
    name,
    value,
    day,
    category_id,
    credit_card_id
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, name, value, day, category_id, credit_card_id, created_at, updated_at
`

type CreateMonthlyTransactionParams struct {
	UserID       uuid.UUID      `json:"user_id"`
	Name         string         `json:"name"`
	Value        pgtype.Numeric `json:"value"`
	Day          int32          `json:"day"`
	CategoryID   uuid.UUID      `json:"category_id"`
	CreditCardID pgtype.UUID    `json:"credit_card_id"`
}

func (q *Queries) CreateMonthlyTransaction(ctx context.Context, arg CreateMonthlyTransactionParams) (MonthlyTransaction, error) {
	row := q.db.QueryRow(ctx, createMonthlyTransaction,
		arg.UserID,
		arg.Name,
		arg.Value,
		arg.Day,
		arg.CategoryID,
		arg.CreditCardID,
	)
	var i MonthlyTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Value,
		&i.Day,
		&i.CategoryID,
		&i.CreditCardID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMonthlyTransaction = `-- name: DeleteMonthlyTransaction :exec
DELETE FROM monthly_transactions
WHERE id = $1
`

func (q *Queries) DeleteMonthlyTransaction(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMonthlyTransaction, id)
	return err
}

const getMonthlyTransactionByID = `-- name: GetMonthlyTransactionByID :one
SELECT id, user_id, name, value, day, category_id, credit_card_id, created_at, updated_at
FROM monthly_transactions
WHERE id = $1
`

func (q *Queries) GetMonthlyTransactionByID(ctx context.Context, id uuid.UUID) (MonthlyTransaction, error) {
	row := q.db.QueryRow(ctx, getMonthlyTransactionByID, id)
	var i MonthlyTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Value,
		&i.Day,
		&i.CategoryID,
		&i.CreditCardID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMonthlyTransactionsByUserIDPaginated = `-- name: ListMonthlyTransactionsByUserIDPaginated :many
SELECT 
    id,
    user_id,
    name,
    value,
    day,
    category_id,
    credit_card_id,
    created_at,
    updated_at,
    COUNT(*) OVER() as total_count
FROM monthly_transactions
WHERE user_id = $1
ORDER BY day ASC
LIMIT $2 OFFSET $3
`

type ListMonthlyTransactionsByUserIDPaginatedParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListMonthlyTransactionsByUserIDPaginatedRow struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	Name         string             `json:"name"`
	Value        pgtype.Numeric     `json:"value"`
	Day          int32              `json:"day"`
	CategoryID   uuid.UUID          `json:"category_id"`
	CreditCardID pgtype.UUID        `json:"credit_card_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	TotalCount   int64              `json:"total_count"`
}

func (q *Queries) ListMonthlyTransactionsByUserIDPaginated(ctx context.Context, arg ListMonthlyTransactionsByUserIDPaginatedParams) ([]ListMonthlyTransactionsByUserIDPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listMonthlyTransactionsByUserIDPaginated, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMonthlyTransactionsByUserIDPaginatedRow
	for rows.Next() {
		var i ListMonthlyTransactionsByUserIDPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Value,
			&i.Day,
			&i.CategoryID,
			&i.CreditCardID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMonthlyTransaction = `-- name: UpdateMonthlyTransaction :one
UPDATE monthly_transactions
SET
    name = $2,
    value = $3,
    day = $4,
    category_id = $5,
    credit_card_id = $6,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, value, day, category_id, credit_card_id, created_at, updated_at
`

type UpdateMonthlyTransactionParams struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	Value        pgtype.Numeric `json:"value"`
	Day          int32          `json:"day"`
	CategoryID   uuid.UUID      `json:"category_id"`
	CreditCardID pgtype.UUID    `json:"credit_card_id"`
}

func (q *Queries) UpdateMonthlyTransaction(ctx context.Context, arg UpdateMonthlyTransactionParams) (MonthlyTransaction, error) {
	row := q.db.QueryRow(ctx, updateMonthlyTransaction,
		arg.ID,
		arg.Name,
		arg.Value,
		arg.Day,
		arg.CategoryID,
		arg.CreditCardID,
	)
	var i MonthlyTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Value,
		&i.Day,
		&i.CategoryID,
		&i.CreditCardID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
