// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    user_id,
    name,
    date,
    value,
    category_id,
    credit_card_id,
    monthly_transactions_id,
    annual_transactions_id,
    installment_transactions_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, user_id, name, date, value, category_id, credit_card_id, monthly_transactions_id, annual_transactions_id, installment_transactions_id, created_at, updated_at
`

type CreateTransactionParams struct {
	UserID                    uuid.UUID          `json:"user_id"`
	Name                      string             `json:"name"`
	Date                      pgtype.Timestamptz `json:"date"`
	Value                     pgtype.Numeric     `json:"value"`
	CategoryID                uuid.UUID          `json:"category_id"`
	CreditCardID              pgtype.UUID        `json:"credit_card_id"`
	MonthlyTransactionsID     pgtype.UUID        `json:"monthly_transactions_id"`
	AnnualTransactionsID      pgtype.UUID        `json:"annual_transactions_id"`
	InstallmentTransactionsID pgtype.UUID        `json:"installment_transactions_id"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.Name,
		arg.Date,
		arg.Value,
		arg.CategoryID,
		arg.CreditCardID,
		arg.MonthlyTransactionsID,
		arg.AnnualTransactionsID,
		arg.InstallmentTransactionsID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Date,
		&i.Value,
		&i.CategoryID,
		&i.CreditCardID,
		&i.MonthlyTransactionsID,
		&i.AnnualTransactionsID,
		&i.InstallmentTransactionsID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions
WHERE id = $1
`

func (q *Queries) DeleteTransaction(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTransaction, id)
	return err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, user_id, name, date, value, category_id, credit_card_id, monthly_transactions_id, annual_transactions_id, installment_transactions_id, created_at, updated_at
FROM transactions
WHERE id = $1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Date,
		&i.Value,
		&i.CategoryID,
		&i.CreditCardID,
		&i.MonthlyTransactionsID,
		&i.AnnualTransactionsID,
		&i.InstallmentTransactionsID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTransactionsByUserAndDate = `-- name: ListTransactionsByUserAndDate :many
SELECT 
    id, user_id, name, date, value, category_id, credit_card_id, monthly_transactions_id, annual_transactions_id, installment_transactions_id, created_at, updated_at,
    COUNT(*) OVER() as total_count
FROM transactions
WHERE user_id = $1
  AND date >= $2
  AND date <= $3
ORDER BY date DESC
LIMIT $3 OFFSET $4
`

type ListTransactionsByUserAndDateParams struct {
	UserID uuid.UUID          `json:"user_id"`
	Date   pgtype.Timestamptz `json:"date"`
	Limit  int32              `json:"limit"`
	Offset int32              `json:"offset"`
}

type ListTransactionsByUserAndDateRow struct {
	ID                        uuid.UUID          `json:"id"`
	UserID                    uuid.UUID          `json:"user_id"`
	Name                      string             `json:"name"`
	Date                      pgtype.Timestamptz `json:"date"`
	Value                     pgtype.Numeric     `json:"value"`
	CategoryID                uuid.UUID          `json:"category_id"`
	CreditCardID              pgtype.UUID        `json:"credit_card_id"`
	MonthlyTransactionsID     pgtype.UUID        `json:"monthly_transactions_id"`
	AnnualTransactionsID      pgtype.UUID        `json:"annual_transactions_id"`
	InstallmentTransactionsID pgtype.UUID        `json:"installment_transactions_id"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	TotalCount                int64              `json:"total_count"`
}

func (q *Queries) ListTransactionsByUserAndDate(ctx context.Context, arg ListTransactionsByUserAndDateParams) ([]ListTransactionsByUserAndDateRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsByUserAndDate,
		arg.UserID,
		arg.Date,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsByUserAndDateRow
	for rows.Next() {
		var i ListTransactionsByUserAndDateRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Date,
			&i.Value,
			&i.CategoryID,
			&i.CreditCardID,
			&i.MonthlyTransactionsID,
			&i.AnnualTransactionsID,
			&i.InstallmentTransactionsID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByUserIDPaginated = `-- name: ListTransactionsByUserIDPaginated :many
SELECT 
    id,
    user_id,
    name,
    date,
    value,
    category_id,
    credit_card_id,
    monthly_transactions_id,
    annual_transactions_id,
    installment_transactions_id,
    created_at,
    updated_at,
    COUNT(*) OVER() as total_count
FROM transactions
WHERE user_id = $1
ORDER BY date DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsByUserIDPaginatedParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListTransactionsByUserIDPaginatedRow struct {
	ID                        uuid.UUID          `json:"id"`
	UserID                    uuid.UUID          `json:"user_id"`
	Name                      string             `json:"name"`
	Date                      pgtype.Timestamptz `json:"date"`
	Value                     pgtype.Numeric     `json:"value"`
	CategoryID                uuid.UUID          `json:"category_id"`
	CreditCardID              pgtype.UUID        `json:"credit_card_id"`
	MonthlyTransactionsID     pgtype.UUID        `json:"monthly_transactions_id"`
	AnnualTransactionsID      pgtype.UUID        `json:"annual_transactions_id"`
	InstallmentTransactionsID pgtype.UUID        `json:"installment_transactions_id"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	TotalCount                int64              `json:"total_count"`
}

func (q *Queries) ListTransactionsByUserIDPaginated(ctx context.Context, arg ListTransactionsByUserIDPaginatedParams) ([]ListTransactionsByUserIDPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsByUserIDPaginated, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsByUserIDPaginatedRow
	for rows.Next() {
		var i ListTransactionsByUserIDPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Date,
			&i.Value,
			&i.CategoryID,
			&i.CreditCardID,
			&i.MonthlyTransactionsID,
			&i.AnnualTransactionsID,
			&i.InstallmentTransactionsID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET
    name = $2,
    date = $3,
    value = $4,
    category_id = $5,
    credit_card_id = $6,
    monthly_transactions_id = $7,
    annual_transactions_id = $8,
    installment_transactions_id = $9,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, date, value, category_id, credit_card_id, monthly_transactions_id, annual_transactions_id, installment_transactions_id, created_at, updated_at
`

type UpdateTransactionParams struct {
	ID                        uuid.UUID          `json:"id"`
	Name                      string             `json:"name"`
	Date                      pgtype.Timestamptz `json:"date"`
	Value                     pgtype.Numeric     `json:"value"`
	CategoryID                uuid.UUID          `json:"category_id"`
	CreditCardID              pgtype.UUID        `json:"credit_card_id"`
	MonthlyTransactionsID     pgtype.UUID        `json:"monthly_transactions_id"`
	AnnualTransactionsID      pgtype.UUID        `json:"annual_transactions_id"`
	InstallmentTransactionsID pgtype.UUID        `json:"installment_transactions_id"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.Name,
		arg.Date,
		arg.Value,
		arg.CategoryID,
		arg.CreditCardID,
		arg.MonthlyTransactionsID,
		arg.AnnualTransactionsID,
		arg.InstallmentTransactionsID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Date,
		&i.Value,
		&i.CategoryID,
		&i.CreditCardID,
		&i.MonthlyTransactionsID,
		&i.AnnualTransactionsID,
		&i.InstallmentTransactionsID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
